const DB_TYPE_MAKEUPS = 'makeups'
const DB_TYPE_MAKEUPS_DONE = 'makeups-done'
const DB_TYPE_STUDENTS = 'students'
const DB_TYPE_STUDENT_SONGS = 'student-songs'
const DB_TYPE_EVENT_DATES = 'event-dates'
const DB_TYPE_JOKES = 'jokes'
const DB_TYPE_USERS = 'users'

const dbTypes = {
  DB_TYPE_MAKEUPS,
  DB_TYPE_MAKEUPS_DONE,
  DB_TYPE_STUDENTS,
  DB_TYPE_STUDENT_SONGS,
  DB_TYPE_EVENT_DATES,
  DB_TYPE_JOKES,
  DB_TYPE_USERS
}

export { 
  dbTypes,
  DB_TYPE_MAKEUPS,
  DB_TYPE_MAKEUPS_DONE,
  DB_TYPE_STUDENTS,
  DB_TYPE_STUDENT_SONGS,
  DB_TYPE_EVENT_DATES,
  DB_TYPE_JOKES,
  DB_TYPE_USERS
}